defmodule ElixirKatasWeb.PhoenixKata16RestfulResourcesLive do
  use ElixirKatasWeb, :live_component

  def phoenix_source do
    """
    # One line generates 7 RESTful routes:
    resources "/products", ProductController

    # GET     /products          :index   — List all
    # GET     /products/new      :new     — New form
    # POST    /products          :create  — Create
    # GET     /products/:id      :show    — Show one
    # GET     /products/:id/edit :edit    — Edit form
    # PUT     /products/:id      :update  — Update
    # DELETE  /products/:id      :delete  — Delete

    # Controller with all CRUD actions:
    defmodule MyAppWeb.ProductController do
      use MyAppWeb, :controller

      def index(conn, _params) do
        products = Catalog.list_products()
        render(conn, :index, products: products)
      end

      def show(conn, %{"id" => id}) do
        product = Catalog.get_product!(id)
        render(conn, :show, product: product)
      end

      def new(conn, _params) do
        changeset = Catalog.change_product(%Product{})
        render(conn, :new, changeset: changeset)
      end

      def create(conn, %{"product" => product_params}) do
        case Catalog.create_product(product_params) do
          {:ok, product} ->
            conn
            |> put_flash(:info, "Product created!")
            |> redirect(to: ~p"/products/\#{product}")

          {:error, changeset} ->
            render(conn, :new, changeset: changeset)
        end
      end

      def delete(conn, %{"id" => id}) do
        product = Catalog.get_product!(id)
        {:ok, _} = Catalog.delete_product(product)

        conn
        |> put_flash(:info, "Product deleted!")
        |> redirect(to: ~p"/products")
      end
    end

    # Customize with :only and :except
    resources "/products", ProductController, only: [:index, :show]
    resources "/users", UserController, except: [:delete]

    # Router with resources
    scope "/", MyAppWeb do
      pipe_through :browser
      resources "/products", ProductController
    end

    # API — no form actions needed
    scope "/api", MyAppWeb.API do
      pipe_through :api
      resources "/products", ProductController,
        only: [:index, :show, :create, :update, :delete]
    end
    """
    |> String.trim()
  end

  @all_actions [
    %{action: :index, method: "GET", path_suffix: "", desc: "List all"},
    %{action: :new, method: "GET", path_suffix: "/new", desc: "New form"},
    %{action: :create, method: "POST", path_suffix: "", desc: "Create"},
    %{action: :show, method: "GET", path_suffix: "/:id", desc: "Show one"},
    %{action: :edit, method: "GET", path_suffix: "/:id/edit", desc: "Edit form"},
    %{action: :update, method: "PUT/PATCH", path_suffix: "/:id", desc: "Update"},
    %{action: :delete, method: "DELETE", path_suffix: "/:id", desc: "Delete"}
  ]

  def mount(socket) do
    {:ok,
     assign(socket,
       active_tab: "routes",
       resource_name: "products",
       selected_actions: MapSet.new([:index, :new, :create, :show, :edit, :update, :delete]),
       filter_mode: "all",
       selected_action: :index
     )}
  end

  def update(assigns, socket) do
    {:ok, assign(socket, id: assigns.id)}
  end

  def render(assigns) do
    ~H"""
    <div class="space-y-6">
      <h2 class="text-2xl font-bold text-gray-900 dark:text-white">RESTful Resources</h2>
      <p class="text-gray-600 dark:text-gray-300">
        One line of code, seven routes. The <code>resources</code> macro generates all CRUD routes automatically.
      </p>

      <!-- Tabs -->
      <div class="flex gap-1 border-b border-gray-200 dark:border-gray-700">
        <button
          :for={tab <- ["routes", "controller", "customize", "code"]}
          phx-click="switch_tab"
          phx-target={@myself}
          phx-value-tab={tab}
          class={["px-4 py-2 text-sm font-medium rounded-t-lg transition-colors cursor-pointer",
            if(@active_tab == tab,
              do: "bg-teal-50 dark:bg-teal-900/30 text-teal-700 dark:text-teal-400 border-b-2 border-teal-600",
              else: "text-gray-500 hover:text-gray-700 dark:hover:text-gray-300")]}
        >
          {tab_label(tab)}
        </button>
      </div>

      <!-- Route table -->
      <%= if @active_tab == "routes" do %>
        <div class="space-y-4">
          <p class="text-sm text-gray-600 dark:text-gray-300">
            Type a resource name to see the routes generated by <code>resources</code>.
          </p>

          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Resource name</label>
            <input type="text" phx-change="update_resource" phx-target={@myself} name="name" value={@resource_name}
              class="w-full max-w-xs rounded-lg border-gray-300 dark:border-gray-600 dark:bg-gray-700 text-sm font-mono"
              placeholder="products" />
          </div>

          <!-- Quick presets -->
          <div class="flex flex-wrap gap-2">
            <button :for={name <- ["products", "users", "posts", "comments", "sessions"]}
              phx-click="set_resource"
              phx-target={@myself}
              phx-value-name={name}
              class="px-3 py-1 text-xs rounded-full bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 font-mono cursor-pointer">
              {name}
            </button>
          </div>

          <!-- Router code -->
          <div class="bg-gray-900 rounded-lg p-4 font-mono text-sm text-green-400 overflow-x-auto">
            <span class="text-gray-500">resources</span> <span class="text-amber-400">"/{@resource_name}"</span>, <span class="text-blue-400">{controller_name(@resource_name)}</span>
          </div>

          <!-- Route table -->
          <div class="overflow-x-auto">
            <table class="w-full text-sm">
              <thead>
                <tr class="text-left text-gray-500 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">
                  <th class="py-2 pr-4">Method</th>
                  <th class="py-2 pr-4">Path</th>
                  <th class="py-2 pr-4">Action</th>
                  <th class="py-2">Purpose</th>
                </tr>
              </thead>
              <tbody>
                <%= for route <- all_actions() do %>
                  <tr
                    phx-click="select_action"
                    phx-target={@myself}
                    phx-value-action={to_string(route.action)}
                    class={["border-b border-gray-100 dark:border-gray-800 cursor-pointer transition-colors",
                      if(@selected_action == route.action,
                        do: "bg-teal-50 dark:bg-teal-900/20",
                        else: "hover:bg-gray-50 dark:hover:bg-gray-800")]}
                  >
                    <td class="py-2 pr-4">
                      <span class={["px-2 py-0.5 rounded text-xs font-bold", method_color(route.method)]}>
                        {route.method}
                      </span>
                    </td>
                    <td class="py-2 pr-4 font-mono text-gray-700 dark:text-gray-300">
                      /{@resource_name}{route.path_suffix}
                    </td>
                    <td class="py-2 pr-4 font-mono text-blue-600 dark:text-blue-400">
                      :{route.action}
                    </td>
                    <td class="py-2 text-gray-500 dark:text-gray-400">{route.desc}</td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

          <!-- Action detail -->
          <div class="p-4 rounded-lg bg-gray-900 font-mono text-sm text-green-400 overflow-x-auto whitespace-pre">{action_code(@selected_action, @resource_name)}</div>
        </div>
      <% end %>

      <!-- Controller -->
      <%= if @active_tab == "controller" do %>
        <div class="space-y-4">
          <p class="text-sm text-gray-600 dark:text-gray-300">
            Each resource action maps to a function in the controller. Click an action to see its implementation.
          </p>

          <div class="grid grid-cols-2 sm:grid-cols-4 md:grid-cols-7 gap-2">
            <%= for route <- all_actions() do %>
              <button
                phx-click="select_action"
                phx-target={@myself}
                phx-value-action={to_string(route.action)}
                class={["px-3 py-2 rounded-lg text-xs font-mono font-semibold cursor-pointer transition-colors",
                  if(@selected_action == route.action,
                    do: "bg-teal-600 text-white",
                    else: "bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600")]}
              >
                :{route.action}
              </button>
            <% end %>
          </div>

          <div class="bg-gray-900 rounded-lg p-4 font-mono text-sm text-green-400 overflow-x-auto whitespace-pre">{controller_action_code(@selected_action)}</div>
        </div>
      <% end %>

      <!-- Customize -->
      <%= if @active_tab == "customize" do %>
        <div class="space-y-4">
          <p class="text-sm text-gray-600 dark:text-gray-300">
            Toggle actions to see how <code>:only</code> and <code>:except</code> work. Click actions to include/exclude them.
          </p>

          <!-- Action toggles -->
          <div class="flex flex-wrap gap-2">
            <%= for route <- all_actions() do %>
              <button
                phx-click="toggle_action"
                phx-target={@myself}
                phx-value-action={to_string(route.action)}
                class={["px-3 py-2 rounded-lg text-xs font-mono font-semibold cursor-pointer transition-colors border-2",
                  if(MapSet.member?(@selected_actions, route.action),
                    do: "bg-teal-50 dark:bg-teal-900/30 border-teal-400 text-teal-700 dark:text-teal-300",
                    else: "bg-gray-50 dark:bg-gray-800 border-gray-300 dark:border-gray-600 text-gray-400 line-through")]}
              >
                :{route.action}
              </button>
            <% end %>
          </div>

          <!-- Quick presets -->
          <div class="flex flex-wrap gap-2">
            <button :for={{label, actions} <- filter_presets()}
              phx-click="set_filter"
              phx-target={@myself}
              phx-value-filter={label}
              class="px-3 py-1 text-xs rounded-full bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-300 hover:bg-amber-200 dark:hover:bg-amber-800 cursor-pointer">
              {label} ({length(actions)})
            </button>
          </div>

          <!-- Generated code -->
          <div class="bg-gray-900 rounded-lg p-4 font-mono text-sm text-green-400 overflow-x-auto whitespace-pre">{customize_code(@resource_name, @selected_actions)}</div>

          <!-- Resulting routes -->
          <h4 class="font-semibold text-gray-700 dark:text-gray-300">Generated Routes</h4>
          <div class="overflow-x-auto">
            <table class="w-full text-sm">
              <thead>
                <tr class="text-left text-gray-500 dark:text-gray-400 border-b border-gray-200 dark:border-gray-700">
                  <th class="py-2 pr-4">Method</th>
                  <th class="py-2 pr-4">Path</th>
                  <th class="py-2">Action</th>
                </tr>
              </thead>
              <tbody>
                <%= for route <- all_actions(), MapSet.member?(@selected_actions, route.action) do %>
                  <tr class="border-b border-gray-100 dark:border-gray-800">
                    <td class="py-2 pr-4">
                      <span class={["px-2 py-0.5 rounded text-xs font-bold", method_color(route.method)]}>{route.method}</span>
                    </td>
                    <td class="py-2 pr-4 font-mono text-gray-700 dark:text-gray-300">/{@resource_name}{route.path_suffix}</td>
                    <td class="py-2 font-mono text-blue-600 dark:text-blue-400">:{route.action}</td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      <% end %>

      <!-- Full code -->
      <%= if @active_tab == "code" do %>
        <div class="space-y-4">
          <h4 class="font-semibold text-gray-700 dark:text-gray-300">Complete Router with Resources</h4>
          <div class="bg-gray-900 rounded-lg p-4 font-mono text-sm text-green-400 overflow-x-auto whitespace-pre">{full_router_code()}</div>
        </div>
      <% end %>
    </div>
    """
  end

  def handle_event("switch_tab", %{"tab" => tab}, socket) do
    {:noreply, assign(socket, active_tab: tab)}
  end

  def handle_event("update_resource", %{"name" => name}, socket) do
    {:noreply, assign(socket, resource_name: name)}
  end

  def handle_event("set_resource", %{"name" => name}, socket) do
    {:noreply, assign(socket, resource_name: name)}
  end

  def handle_event("select_action", %{"action" => action}, socket) do
    {:noreply, assign(socket, selected_action: String.to_existing_atom(action))}
  end

  def handle_event("toggle_action", %{"action" => action}, socket) do
    atom = String.to_existing_atom(action)
    actions = socket.assigns.selected_actions

    new_actions =
      if MapSet.member?(actions, atom),
        do: MapSet.delete(actions, atom),
        else: MapSet.put(actions, atom)

    {:noreply, assign(socket, selected_actions: new_actions)}
  end

  def handle_event("set_filter", %{"filter" => label}, socket) do
    presets = filter_presets()
    actions = Keyword.get(presets, String.to_atom(label), [])
    {:noreply, assign(socket, selected_actions: MapSet.new(actions))}
  end

  defp tab_label("routes"), do: "Route Table"
  defp tab_label("controller"), do: "Controller"
  defp tab_label("customize"), do: "Only / Except"
  defp tab_label("code"), do: "Source Code"

  defp all_actions, do: @all_actions

  defp controller_name(resource) do
    resource
    |> String.split("_")
    |> Enum.map(&String.capitalize/1)
    |> Enum.join()
    |> then(&"#{&1}Controller")
  end

  defp method_color("GET"), do: "bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400"
  defp method_color("POST"), do: "bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-400"
  defp method_color("PUT/PATCH"), do: "bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400"
  defp method_color("DELETE"), do: "bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400"

  defp filter_presets do
    [
      "All 7": [:index, :new, :create, :show, :edit, :update, :delete],
      "API only": [:index, :show, :create, :update, :delete],
      "Read only": [:index, :show],
      "No delete": [:index, :new, :create, :show, :edit, :update],
      "Create only": [:new, :create]
    ]
  end

  defp action_code(:index, resource) do
    """
    # GET /#{resource}
    def index(conn, _params) do
      #{resource} = Catalog.list_#{resource}()
      render(conn, :index, #{resource}: #{resource})
    end\
    """
    |> String.trim()
  end

  defp action_code(:new, resource) do
    singular = String.trim_trailing(resource, "s")

    """
    # GET /#{resource}/new
    def new(conn, _params) do
      changeset = Catalog.change_#{singular}(%#{String.capitalize(singular)}{})
      render(conn, :new, changeset: changeset)
    end\
    """
    |> String.trim()
  end

  defp action_code(:create, resource) do
    singular = String.trim_trailing(resource, "s")

    """
    # POST /#{resource}
    def create(conn, %{"#{singular}" => #{singular}_params}) do
      case Catalog.create_#{singular}(#{singular}_params) do
        {:ok, #{singular}} ->
          conn
          |> put_flash(:info, "#{String.capitalize(singular)} created!")
          |> redirect(to: ~p"/#{resource}/\#{#{singular}}")

        {:error, changeset} ->
          render(conn, :new, changeset: changeset)
      end
    end\
    """
    |> String.trim()
  end

  defp action_code(:show, resource) do
    singular = String.trim_trailing(resource, "s")

    """
    # GET /#{resource}/:id
    def show(conn, %{"id" => id}) do
      #{singular} = Catalog.get_#{singular}!(id)
      render(conn, :show, #{singular}: #{singular})
    end\
    """
    |> String.trim()
  end

  defp action_code(:edit, resource) do
    singular = String.trim_trailing(resource, "s")

    """
    # GET /#{resource}/:id/edit
    def edit(conn, %{"id" => id}) do
      #{singular} = Catalog.get_#{singular}!(id)
      changeset = Catalog.change_#{singular}(#{singular})
      render(conn, :edit, #{singular}: #{singular}, changeset: changeset)
    end\
    """
    |> String.trim()
  end

  defp action_code(:update, resource) do
    singular = String.trim_trailing(resource, "s")

    """
    # PUT/PATCH /#{resource}/:id
    def update(conn, %{"id" => id, "#{singular}" => #{singular}_params}) do
      #{singular} = Catalog.get_#{singular}!(id)

      case Catalog.update_#{singular}(#{singular}, #{singular}_params) do
        {:ok, #{singular}} ->
          conn
          |> put_flash(:info, "#{String.capitalize(singular)} updated!")
          |> redirect(to: ~p"/#{resource}/\#{#{singular}}")

        {:error, changeset} ->
          render(conn, :edit, #{singular}: #{singular}, changeset: changeset)
      end
    end\
    """
    |> String.trim()
  end

  defp action_code(:delete, resource) do
    singular = String.trim_trailing(resource, "s")

    """
    # DELETE /#{resource}/:id
    def delete(conn, %{"id" => id}) do
      #{singular} = Catalog.get_#{singular}!(id)
      {:ok, _} = Catalog.delete_#{singular}(#{singular})

      conn
      |> put_flash(:info, "#{String.capitalize(singular)} deleted!")
      |> redirect(to: ~p"/#{resource}")
    end\
    """
    |> String.trim()
  end

  defp controller_action_code(:index) do
    """
    def index(conn, _params) do
      products = Catalog.list_products()
      render(conn, :index, products: products)
    end\
    """
    |> String.trim()
  end

  defp controller_action_code(:new) do
    """
    def new(conn, _params) do
      changeset = Catalog.change_product(%Product{})
      render(conn, :new, changeset: changeset)
    end\
    """
    |> String.trim()
  end

  defp controller_action_code(:create) do
    """
    def create(conn, %{"product" => product_params}) do
      case Catalog.create_product(product_params) do
        {:ok, product} ->
          conn
          |> put_flash(:info, "Product created!")
          |> redirect(to: ~p"/products/\#{product}")

        {:error, changeset} ->
          render(conn, :new, changeset: changeset)
      end
    end\
    """
    |> String.trim()
  end

  defp controller_action_code(:show) do
    """
    def show(conn, %{"id" => id}) do
      product = Catalog.get_product!(id)
      render(conn, :show, product: product)
    end\
    """
    |> String.trim()
  end

  defp controller_action_code(:edit) do
    """
    def edit(conn, %{"id" => id}) do
      product = Catalog.get_product!(id)
      changeset = Catalog.change_product(product)
      render(conn, :edit, product: product, changeset: changeset)
    end\
    """
    |> String.trim()
  end

  defp controller_action_code(:update) do
    """
    def update(conn, %{"id" => id, "product" => product_params}) do
      product = Catalog.get_product!(id)

      case Catalog.update_product(product, product_params) do
        {:ok, product} ->
          conn
          |> put_flash(:info, "Product updated!")
          |> redirect(to: ~p"/products/\#{product}")

        {:error, changeset} ->
          render(conn, :edit, product: product, changeset: changeset)
      end
    end\
    """
    |> String.trim()
  end

  defp controller_action_code(:delete) do
    """
    def delete(conn, %{"id" => id}) do
      product = Catalog.get_product!(id)
      {:ok, _} = Catalog.delete_product(product)

      conn
      |> put_flash(:info, "Product deleted!")
      |> redirect(to: ~p"/products")
    end\
    """
    |> String.trim()
  end

  defp customize_code(resource, selected_actions) do
    all = [:index, :new, :create, :show, :edit, :update, :delete]
    selected = Enum.filter(all, &MapSet.member?(selected_actions, &1))
    excluded = all -- selected

    cond do
      length(selected) == 7 ->
        "resources \"/#{resource}\", #{controller_name(resource)}"

      length(selected) <= 3 ->
        actions_str = Enum.map(selected, &":#{&1}") |> Enum.join(", ")
        "resources \"/#{resource}\", #{controller_name(resource)},\n  only: [#{actions_str}]"

      length(excluded) <= 3 ->
        actions_str = Enum.map(excluded, &":#{&1}") |> Enum.join(", ")
        "resources \"/#{resource}\", #{controller_name(resource)},\n  except: [#{actions_str}]"

      true ->
        actions_str = Enum.map(selected, &":#{&1}") |> Enum.join(", ")
        "resources \"/#{resource}\", #{controller_name(resource)},\n  only: [#{actions_str}]"
    end
  end

  defp full_router_code do
    """
    defmodule MyAppWeb.Router do
      use MyAppWeb, :router

      pipeline :browser do
        plug :accepts, ["html"]
        plug :fetch_session
        plug :fetch_live_flash
        plug :put_root_layout, html: {MyAppWeb.Layouts, :root}
        plug :protect_from_forgery
        plug :put_secure_browser_headers
      end

      pipeline :api do
        plug :accepts, ["json"]
      end

      # Browser routes — full CRUD with forms
      scope "/", MyAppWeb do
        pipe_through :browser

        get "/", PageController, :home
        resources "/products", ProductController
        resources "/users", UserController, only: [:index, :show]
      end

      # API routes — no form actions needed
      scope "/api", MyAppWeb.API do
        pipe_through :api

        resources "/products", ProductController,
          only: [:index, :show, :create, :update, :delete]
      end
    end\
    """
    |> String.trim()
  end
end
